import Image from "next/image";
import Link from "next/link";
import { Sparkles, Gauge, Network, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { RippleCanvas } from "@/components/research-radar/ripple-canvas";
import { LandingCodeCard } from "@/components/research-radar/landing-code-card";
import { LandingApproach } from "@/components/research-radar/landing-approach";
import { FadeInSection } from "@/components/research-radar/fade-in-section";

const PILLARS = [
  {
    icon: Sparkles,
    title: "AI-estimated analysis",
    description:
      "Every paper and repo gets a neutral summary, core methodology breakdown, and three developer-focused takeaways generated by AI.",
  },
  {
    icon: Gauge,
    title: "Technical difficulty scoring",
    description:
      "A 1-10 AI-estimated difficulty score and beginner/intermediate/expert label help you triage what's worth your time.",
  },
  {
    icon: Network,
    title: "Related research",
    description:
      "pgvector similarity search surfaces related papers and repos so you can follow a thread across sources.",
  },
];

export function LandingPage() {
  return (
    <div className="flex min-h-screen flex-col bg-sky-50 text-sky-950">
      {/* Ocean hero */}
      <div className="relative overflow-hidden">
        <video
          src="/ocean-hero.mp4"
          poster="/ocean-hero-poster.jpg"
          autoPlay
          muted
          loop
          playsInline
          className="pointer-events-none absolute inset-0 z-0 h-full w-full object-cover object-[50%_30%]"
        />
        <div className="pointer-events-none absolute inset-0 z-0 bg-gradient-to-b from-slate-950/70 via-slate-950/45 to-sky-50" />
        <RippleCanvas className="pointer-events-none absolute inset-0 z-0 h-full w-full" />

        {/* Header */}
        <header className="relative z-10 mx-auto flex w-full max-w-7xl items-center justify-between px-6 py-5">
          <Link href="/" className="flex items-center gap-2">
            <Image src="/icon.svg" alt="" width={24} height={24} className="size-6" />
            <span className="text-lg font-bold text-white">Research Radar</span>
            <span className="rounded-md border border-white/20 bg-white/10 px-1.5 py-0.5 font-mono text-[10px] font-medium tracking-wide text-white/80 uppercase">
              Beta
            </span>
          </Link>
          <div className="flex items-center gap-3">
            <Button
              variant="ghost"
              nativeButton={false}
              className="text-white/80 hover:bg-white/10 hover:text-white"
              render={<Link href="/sign-in">Sign in</Link>}
            />
            <Button
              nativeButton={false}
              className="bg-white text-sky-950 hover:bg-white/90"
              render={<Link href="/sign-up">Get started</Link>}
            />
          </div>
        </header>

        {/* Hero */}
        <section className="relative z-10 mx-auto grid w-full max-w-7xl grid-cols-1 items-center gap-9 px-6 pt-8 pb-40 md:grid-cols-[55fr_45fr]">
          <div className="flex flex-col gap-6">
            <p className="text-sm font-medium tracking-tight text-white/70">Research Radar · AI research digest</p>
            <h1 className="text-4xl leading-[1.1] font-bold text-white sm:text-6xl">
              Track the papers and repos that matter
            </h1>
            <div className="flex max-w-lg flex-col gap-2 text-white/70">
              <p>arXiv, technical blogs, and trending repos generate more than anyone can read.</p>
              <p>Research Radar scans them, then uses AI to summarize, score difficulty, and link related work.</p>
            </div>
            <div className="mt-2 flex flex-wrap items-center gap-3">
              <Button
                size="lg"
                nativeButton={false}
                className="bg-white text-sky-950 hover:bg-white/90"
                render={
                  <Link href="/sign-up">
                    Get started
                    <ArrowRight data-icon="inline-end" />
                  </Link>
                }
              />
              <Button
                size="lg"
                variant="outline"
                nativeButton={false}
                className="border-white/30 bg-white/10 text-white hover:bg-white/20"
                render={<Link href="/sign-in">Sign in</Link>}
              />
            </div>
          </div>

          <LandingCodeCard />
        </section>
      </div>

      {/* Pillars */}
      <section className="relative z-10 mx-auto w-full max-w-7xl px-6 py-16 text-center">
        <FadeInSection className="mx-auto flex max-w-3xl flex-col items-center gap-5">
          <Badge variant="outline" className="border-sky-900/20 bg-white/70 text-sky-800">
            How it works
          </Badge>
          <h2 className="text-3xl leading-tight font-bold text-sky-950 sm:text-4xl">
            Signal, not noise, from every source you&apos;d never keep up with manually
          </h2>
        </FadeInSection>

        <div className="mt-12 grid grid-cols-1 gap-5 sm:grid-cols-3">
          {PILLARS.map((pillar, index) => (
            <FadeInSection key={pillar.title} delay={index * 120}>
              <Card className="border-sky-900/10 bg-white/70 backdrop-blur-sm">
                <CardContent className="flex flex-col items-center gap-3 py-4 text-center">
                  <pillar.icon className="size-7 text-sky-700" />
                  <h3 className="text-sm font-semibold text-sky-950">{pillar.title}</h3>
                  <p className="text-xs leading-relaxed text-sky-900/70">{pillar.description}</p>
                </CardContent>
              </Card>
            </FadeInSection>
          ))}
        </div>
      </section>

      {/* Design approach */}
      <section className="relative z-10 mx-auto w-full max-w-7xl px-6 py-16">
        <FadeInSection>
          <Badge variant="outline" className="border-sky-900/20 bg-white/70 text-sky-800">
            Under the hood
          </Badge>
          <h2 className="mt-4 mb-9 max-w-2xl text-3xl leading-tight font-bold text-sky-950 sm:text-4xl">
            Every source is scanned. Every paper is scored.
          </h2>
        </FadeInSection>
        <LandingApproach />
      </section>

      {/* Final CTA */}
      <div className="relative overflow-hidden">
        <video
          src="/ocean-sunset.mp4"
          poster="/ocean-sunset-poster.jpg"
          autoPlay
          muted
          loop
          playsInline
          className="pointer-events-none absolute inset-0 z-0 h-full w-full object-cover object-[50%_60%]"
        />
        <div className="pointer-events-none absolute inset-0 z-0 bg-gradient-to-b from-slate-950/60 via-slate-950/55 to-slate-950/70" />

        <FadeInSection>
          <section className="relative z-10 mx-auto flex w-full max-w-7xl flex-col items-center gap-6 px-6 py-24 text-center">
            <h2 className="max-w-2xl text-3xl font-bold text-white sm:text-4xl">
              Start tracking research today
            </h2>
            <p className="max-w-xl text-white/75">
              Free to use. Sign up and your dashboard fills in as new papers and repos are scanned and analyzed.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-3">
              <Button
                size="lg"
                nativeButton={false}
                className="bg-white text-sky-950 hover:bg-white/90"
                render={
                  <Link href="/sign-up">
                    Get started
                    <ArrowRight data-icon="inline-end" />
                  </Link>
                }
              />
              <Button
                size="lg"
                variant="outline"
                nativeButton={false}
                className="border-white/30 bg-white/10 text-white hover:bg-white/20"
                render={<Link href="/sign-in">Sign in</Link>}
              />
            </div>
          </section>
        </FadeInSection>
      </div>

      {/* Footer */}
      <footer className="relative z-10 mx-auto w-full max-w-7xl px-6 pb-8">
        <Separator className="mb-5 bg-sky-900/10" />
        <p className="text-center text-xs text-sky-900/50">
          Research Radar · AI-estimated analysis, not investment or academic advice.
        </p>
      </footer>
    </div>
  );
}
